name: Bug report
description: Create a bug report to help us address errors in the repository
title: "[BUG] <bug description>"
labels:
  - "🚦 status: awaiting triage"
body:
  - type: textarea
    id: bugdescription
    attributes:
      label: Description of the bug
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Please add screenshots (if applicable)
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Add any other context about the problem here
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our [Discord community](https://dsc.gg/learnwithcommunity)
        Feel free to check out our community projects [on our GitHub organization](https://github.com/LearnWithCommunity)
