blank_issues_enabled: false
contact_links:
  - name: Discord community
    url: https://dsc.gg/learnwithcommunity
    about: Feel free to contact any of the repository maintainers via Discord for any queries!
