name: GitHub Invitation
description: I want to join the awesome GitHub organisation
title: "Invite me to the GitHub Community Organization"
labels:
  - "invite me to the organisation"
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Insert your name here
      placeholder: David Leal
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      description: Insert your Discord username here
      placeholder: "Panquesito7#3723"
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Where did you learn about Learn With Community? What do you like about this community/Why do you want to join?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our [Discord community](https://dsc.gg/learnwithcommunity)
        Feel free to check out our community projects [on our GitHub organization](https://github.com/LearnWithCommunity)
